name: Update Version on Release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Extract version from release tag
        id: version
        run: |
          # Remove 'v' prefix from tag if present
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Format the date
          RELEASE_DATE=$(date -d '${{ github.event.release.published_at }}' +%Y-%m-%d)
          echo "date=$RELEASE_DATE" >> $GITHUB_OUTPUT    
            
      - name: Update version.py file
        run: |
          # Update the version and date in utils/version.py
          sed -i 's/BOT_VERSION = "[^"]*"/BOT_VERSION = "${{ steps.version.outputs.version }}"/' utils/version.py
          sed -i 's/BOT_RELEASE_DATE = "[^"]*"/BOT_RELEASE_DATE = "${{ steps.version.outputs.date }}"/' utils/version.py
          
          # Verify the changes
          echo "Updated version.py:"
          cat utils/version.py

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Switch to main branch
          git checkout main
          
          # Apply the changes
          sed -i 's/BOT_VERSION = "[^"]*"/BOT_VERSION = "${{ steps.version.outputs.version }}"/' utils/version.py
          sed -i 's/BOT_RELEASE_DATE = "[^"]*"/BOT_RELEASE_DATE = "${{ steps.version.outputs.date }}"/' utils/version.py
          
          git add utils/version.py
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update version to ${{ steps.version.outputs.version }}"
            git push origin main
          fi
